from collections.abc import Iterable


ROLE_PERMISSIONS: dict[str, set[str]] = {
    "SUPER_ADMIN": {"*"},
    "OPS_ADMIN": {
        "users:write",
        "users:read",
        "cooperatives:read",
        "cooperatives:write",
        "buyers:read",
        "buyers:write",
        "farmers:read",
        "farmers:write",
        "harvests:read",
        "harvests:write",
        "demands:read",
        "demands:write",
        "matching:read",
        "matching:write",
        "transporters:read",
        "transporters:write",
        "vehicles:read",
        "vehicles:write",
        "cold_hubs:read",
        "cold_hubs:write",
        "routes:read",
        "routes:write",
        "jobs:read",
        "jobs:write",
        "proofs:read",
        "proofs:write",
        "temperature:read",
        "temperature:write",
        "payments:write",
        "payments:read",
        "notifications:read",
        "notifications:write",
        "weather:read",
        "reports:read",
        "admin:read",
        "admin:write",
    },
    "COOPERATIVE_ADMIN": {
        "cooperatives:read",
        "cooperatives:write",
        "farmers:read",
        "farmers:write",
        "harvests:read",
        "demands:read",
        "reports:read",
    },
    "FARMER": {
        "farmers:self",
        "farmers:read",
        "harvests:self",
        "harvests:read",
        "harvests:write",
        "demands:read",
        "matching:read",
        "payments:self",
        "proofs:read",
        "temperature:read",
        "notifications:read",
        "weather:read",
    },
    "TRANSPORTER": {
        "transporters:self",
        "vehicles:self",
        "vehicles:read",
        "jobs:self",
        "jobs:read",
        "jobs:write",
        "proofs:self",
        "proofs:read",
        "proofs:write",
        "temperature:write",
        "payments:self",
        "notifications:read",
        "routes:read",
    },
    "BUYER": {
        "buyers:self",
        "buyers:read",
        "buyers:write",
        "demands:self",
        "demands:read",
        "demands:write",
        "matching:read",
        "payments:self",
        "payments:write",
        "harvests:read",
        "notifications:read",
        "weather:read",
    },
    "COLD_HUB_OPERATOR": {
        "cold_hubs:self",
        "cold_hubs:read",
        "cold_hubs:write",
        "temperature:read",
        "temperature:write",
        "routes:read",
        "jobs:read",
    },
    "FINANCE_PARTNER": {"payments:read", "reports:read"},
}


def has_permission(role: str, permission: str | Iterable[str]) -> bool:
    granted = ROLE_PERMISSIONS.get(role, set())
    if "*" in granted:
        return True
    if isinstance(permission, str):
        return permission in granted
    return all(item in granted for item in permission)
